[package]
name = "image_proc"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.8"
rayon = "1.11.0"


[lib]
name = "image_proc_lib"
crate-type = ["cdylib"]
path = "src/pre_proc_lib/src/lib.rs"